#!/bin/sh

# Don't run during a rebase
if [ "$2" = "rebase" ]; then
  exit 0
fi

# Skip for merge commits or squash
if [ "$2" = "merge" ] || [ "$2" = "squash" ]; then
  exit 0
fi

# Otherwise invoke Commitizen
if [ -t 1 ]; then
  exec < /dev/tty && npx cz --hook --edit "$1"
fi