export default {
    extends: ['@commitlint/config-conventional'],
    // Ignore commits automatically generated by the Copilot agent, which append
    // an "Agent-Logs-Url:" trailer that exceeds the 100-char body-max-line-length.
    ignores: [(message) => message.includes('Agent-Logs-Url:')],
};
