export default {
    extends: ['@commitlint/config-conventional'],
    // Ignore commits automatically generated by the Copilot agent, which append
    // an "Agent-Logs-Url:" trailer that exceeds the 100-char body-max-line-length.
    // Also ignore dependabot commits, which include long URLs in the commit body.
    ignores: [
        (message) => message.includes('Agent-Logs-Url:'),
        (message) => message.includes('Signed-off-by: dependabot[bot]'),
    ],
};
