name: Audit Dependencies

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: read

jobs:
    dependency-review:
        name: Dependency Review
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Review Dependency Changes
              uses: actions/dependency-review-action@v4
              with:
                  fail-on-severity: moderate
