name: Lint Commit Messages

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    pull-requests: read

jobs:
    commitlint:
        name: Run Commitlint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v6

            - name: Install Node.js
              uses: actions/setup-node@v7
              with:
                  node-version: 22
                  cache: 'pnpm'
                  cache-dependency-path: |
                      package.json
                      pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install

            - name: Lint commit messages
              run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
