name: Enforce Code Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Check Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code x
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests with Coverage
        run: pnpm test --coverage

      - name: Enforce Coverage Threshold
        run: |
          COVERAGE=$(pnpm test --coverage --coverageReporters=text-summary | grep 'All files' | awk '{print $3}' | sed 's/%//')
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            echo "Code coverage is below 50%. PR cannot be merged."
            exit 1
          fi