name: Upload Extension

on:
    workflow_dispatch:
    release:
        types: [published]

permissions:
    contents: read

jobs:
    submit:
        name: Submit to Store(s)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Install pnpm
              uses: pnpm/action-setup@v6

            - name: Install Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: 'pnpm'
                  cache-dependency-path: |
                      package.json
                      pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install

            - name: Extract release version from tag
              id: extract_version
              run: |
                  echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
            - name: Inject version into package.json
              run: |
                  jq '.version = "${{ steps.extract_version.outputs.VERSION }}"' package.json > package.json.tmp && mv package.json.tmp package.json

            - name: Zip Chrome extension
              run: |
                  pnpm zip

            - name: Submit to Chrome Store
              run: |
                  pnpm wxt submit \
                    --chrome-zip .output/*-chrome.zip \
              env:
                  CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
                  CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
                  CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
                  CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
                  CHROME_SKIP_SUBMIT_REVIEW: true

            - name: Zip Firefox extension
              run: |
                  pnpm zip:firefox

            - name: Submit to Firefox Add-ons
              if: ${{ env.FIREFOX_JWT_ISSUER != '' }}
              run: |
                  pnpm wxt submit \
                    --firefox-zip .output/*-firefox.zip
              env:
                  FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
                  FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
