name: Upload Code Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js and PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests and Generate Coverage
        run: pnpm test --coverage --run

      - name: Move JSON to Public Directory
        run: |
          mkdir -p coverage-report
          cp coverage/coverage-summary.json coverage-report/coverage.json

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: coverage-report