name: Upload Code Coverage

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    test-coverage:
        name: Upload Coverage
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Setup
              uses: ./.github/actions/setup

            - name: Run Tests and Generate Coverage
              run: pnpm test --coverage --run

            - name: Generate Coverage JSON badge
              run: |
                  chmod +x scripts/generate-coverage-badge.sh
                  scripts/generate-coverage-badge.sh

            - name: Move JSON & HTML to Public Directory
              run: |
                  cp coverage/coverage-summary.json coverage-report/coverage.json
                  cp coverage/index.html coverage-report/index.html

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: coverage-report
